name: Build and Deploy GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write  # Required for deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Generate index.md
        run: |
          python3 <<EOF
          import os
          def list_files_recursively(base_path, relative_path=""):
              entries = []
              full_path = os.path.join(base_path, relative_path)
              for entry in sorted(os.listdir(full_path)):
                  if entry.startswith("."):
                      continue
                  entry_rel_path = os.path.join(relative_path, entry)
                  entry_full_path = os.path.join(base_path, entry_rel_path)
                  if os.path.isdir(entry_full_path):
                      entries.append(f"### {entry_rel_path}/\n")
                      entries.extend(list_files_recursively(base_path, entry_rel_path))
                  elif os.path.isfile(entry_full_path):
                      entries.append(f"- [{entry_rel_path}](./cases/{entry_rel_path})")
              return entries

          with open("index.md", "w", encoding="utf-8") as f:
              f.write("# Case Index\n\n")
              f.writelines("\n".join(list_files_recursively("cases")))
          EOF

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.' 

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
